# Generated by Django 3.1.4 on 2021-01-11 19:25

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210111_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, upload_to=auctions.models.rename_image_files),
        ),
    ]
