# Generated by Django 3.1.4 on 2021-01-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(verbose_name='Starting Bid'),
        ),
    ]
