# Generated by Django 3.1.4 on 2021-01-20 21:53

import auctions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_colour',
            field=models.CharField(choices=[('pink', 'pink'), ('peachpuff', 'peach'), ('tan', 'tan'), ('lightgoldrenrod1', 'gold'), ('palegreen1', 'green'), ('paleturquoise1', 'turquoise'), ('lightsteelblue2', 'blue'), ('thistle2', 'thistle')], default=auctions.utils.get_random_colour, max_length=16),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
