# Generated by Django 3.1.4 on 2021-01-20 22:48

import auctions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210120_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bg_colour',
            field=models.CharField(choices=[('pink', 'pink'), ('peachpuff', 'peach'), ('tan', 'tan'), ('palegoldenrod', 'gold'), ('palegreen', 'green'), ('lightcyan', 'cyan'), ('powderblue', 'blue'), ('mediumaquamarine', 'aqua'), ('thistle', 'thistle')], default=auctions.utils.get_random_colour, max_length=16),
        ),
    ]
