# Generated by Django 3.1.4 on 2021-01-22 23:26

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210122_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=auctions.models.get_misc, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.category', verbose_name='Category'),
        ),
    ]
